spring:
  application:
    name: e-micro-service-discovery

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    sever:
      waitTimeInMsWhenSyncEmpty: 0
